### ISSUE TITLE
Tonomy communication continuous integration pipeline in github

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-Communication#16]
Acceptance criteria

* [ ] Github action runs on pull request, it tries to build the app and runs linter

**Comment by HaseebUllahAbbasi** [comment]
just need to add the workflow for linting and building the app followed by the commands  in package.json @theblockstalk

**Comment by theblockstalk** [comment]
looks like this task was already done. please close the PR.
see https://github.com/Tonomy-Foundation/Tonomy-Communication/actions/runs/4428810813/jobs/7768411051 for proof that all the acceptance criteria was already done
